import _ from "lodash";
import { readFileAsString } from "../core/utils";

const {
  env: {
    DEBUG_FOLDER,
    DEBUG_LEVEL,
    ENVIRONMENT,
    PASS_URLS,
    PORT,
    OPENSHIFT_NODEJS_PORT,

    HTTPS_CERT_PATH,
    HTTPS_KEY_PATH,

    DATABASE_HOST,
    DATABASE_INSTANCE,
    DATABASE_NAME,
    DATABASE_PASSWORD,
    DATABASE_PORT,
    DATABASE_USERNAME,

    COOKIE_SECRET,
    SESSION_SECRET,

    LOCAL_PASSWORD_FIELD,
    LOCAL_USERNAME_FIELD,

    LILLY_CLIENT_ID,
    LILLY_CLIENT_SECRET,
    LILLY_ISSUER,
    LILLY_NONCE,
    LILLY_REDIRECT_URI,
    LILLY_SCOPE,
  },
} = process;

export const APP_CONFIG = {
  DEBUG_FOLDER: _.toString(DEBUG_FOLDER),
  DEBUG_LEVEL: _.toString(DEBUG_LEVEL),
  ENVIRONMENT: _.toString(ENVIRONMENT),
  PASS_URLS: _.toString(PASS_URLS),
  PORT: _.toNumber(OPENSHIFT_NODEJS_PORT || PORT),

  HTTPS_CERT: readFileAsString(HTTPS_CERT_PATH),
  HTTPS_KEY: readFileAsString(HTTPS_KEY_PATH),

  DATABASE_HOST: _.toString(DATABASE_HOST),
  DATABASE_INSTANCE: _.toString(DATABASE_INSTANCE),
  DATABASE_NAME: _.toString(DATABASE_NAME),
  DATABASE_PASSWORD: _.toString(DATABASE_PASSWORD),
  DATABASE_PORT: _.toNumber(DATABASE_PORT),
  DATABASE_USERNAME: _.toString(DATABASE_USERNAME),

  COOKIE_SECRET: _.toString(COOKIE_SECRET),
  SESSION_SECRET: _.toString(SESSION_SECRET),

  LOCAL_PASSWORD_FIELD: _.toString(LOCAL_PASSWORD_FIELD),
  LOCAL_USERNAME_FIELD: _.toString(LOCAL_USERNAME_FIELD),

  LILLY_CLIENT_ID: _.toString(LILLY_CLIENT_ID),
  LILLY_CLIENT_SECRET: _.toString(LILLY_CLIENT_SECRET),
  LILLY_ISSUER: _.toString(LILLY_ISSUER),
  LILLY_NONCE: _.toString(LILLY_NONCE),
  LILLY_REDIRECT_URI: _.toString(LILLY_REDIRECT_URI),
  LILLY_SCOPE: _.toString(LILLY_SCOPE),
};
